version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10.3.0
      environment:
        TZ: /usr/share/zoneinfo/Asia/Tokyo
  working_directory: ~/repo

aliases:
  - &restore_cache
      keys:
        - v2-dependencies-{{ checksum "package.json" }}
        - v2-dependencies-
  - &save_cache
      paths:
        - node_modules
      key: v2-dependencies-{{ checksum "package.json" }}

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: yarn install
      - save_cache: *save_cache
      - run: cp config.dev.ts packages/nupp1-shared/src/config.ts
      - run: yarn apollo-codegen:production
      - run: yarn tsc
      - run: yarn lint
      - run: yarn test:coverage --runInBand
